### Horrible-looking code, but it worked ###

library(pdist)
library(StatMatch)
library(Rmisc)
library(plotrix)

citation("pdist")
citation("StatMatch")
citation("Rmisc")
citation("plotrix")

MNdat = read.csv("MNdat.csv", header = TRUE)

ltt <- MNdat[1:4]
ltv <- MNdat[5:8]
ltsy <- MNdat[9:12]
ltsc <-MNdat[13:16]
lth <- MNdat[17:20]

ltt <- na.omit(ltt)
ltv <- na.omit(ltv)
ltsy <- na.omit(ltsy)
ltsc <- na.omit(ltsc)
lth <- na.omit(lth)

MHNtbl = read.csv("MHNtbl.csv", header = TRUE)
MHNtbl <- data.frame(MHNtbl[,-1], row.names=MHNtbl[,1])

MHNtbl[1,1] = mean(mahalanobis.dist(data.x = lth[c(1,2)], data.y = ltsc[c(1,2)], vc=NULL))
MHNtbl[1,2] = mean(mahalanobis.dist(data.x = lth[c(1,3)], data.y = ltsc[c(1,3)], vc=NULL))
MHNtbl[1,3] = mean(mahalanobis.dist(data.x = lth[c(1,4)], data.y = ltsc[c(1,4)], vc=NULL))
MHNtbl[1,4] = mean(mahalanobis.dist(data.x = lth[c(2,3)], data.y = ltsc[c(2,3)], vc=NULL))
MHNtbl[1,5] = mean(mahalanobis.dist(data.x = lth[c(2,4)], data.y = ltsc[c(2,4)], vc=NULL))
MHNtbl[1,6] = mean(mahalanobis.dist(data.x = lth[c(3,4)], data.y = ltsc[c(3,4)], vc=NULL))
MHNtbl[2,1] = mean(mahalanobis.dist(data.x = lth[c(1,2)], data.y = ltsy[c(1,2)], vc=NULL))
MHNtbl[2,2] = mean(mahalanobis.dist(data.x = lth[c(1,3)], data.y = ltsy[c(1,3)], vc=NULL))
MHNtbl[2,3] = mean(mahalanobis.dist(data.x = lth[c(1,4)], data.y = ltsy[c(1,4)], vc=NULL))
MHNtbl[2,4] = mean(mahalanobis.dist(data.x = lth[c(2,3)], data.y = ltsy[c(2,3)], vc=NULL))
MHNtbl[2,5] = mean(mahalanobis.dist(data.x = lth[c(2,4)], data.y = ltsy[c(2,4)], vc=NULL))
MHNtbl[2,6] = mean(mahalanobis.dist(data.x = lth[c(3,4)], data.y = ltsy[c(3,4)], vc=NULL))
MHNtbl[3,1] = mean(mahalanobis.dist(data.x = lth[c(1,2)], data.y = ltt[c(1,2)], vc=NULL))
MHNtbl[3,2] = mean(mahalanobis.dist(data.x = lth[c(1,3)], data.y = ltt[c(1,3)], vc=NULL))
MHNtbl[3,3] = mean(mahalanobis.dist(data.x = lth[c(1,4)], data.y = ltt[c(1,4)], vc=NULL))
MHNtbl[3,4] = mean(mahalanobis.dist(data.x = lth[c(2,3)], data.y = ltt[c(2,3)], vc=NULL))
MHNtbl[3,5] = mean(mahalanobis.dist(data.x = lth[c(2,4)], data.y = ltt[c(2,4)], vc=NULL))
MHNtbl[3,6] = mean(mahalanobis.dist(data.x = lth[c(3,4)], data.y = ltt[c(3,4)], vc=NULL))
MHNtbl[4,1] = mean(mahalanobis.dist(data.x = lth[c(1,2)], data.y = ltv[c(1,2)], vc=NULL))
MHNtbl[4,2] = mean(mahalanobis.dist(data.x = lth[c(1,3)], data.y = ltv[c(1,3)], vc=NULL))
MHNtbl[4,3] = mean(mahalanobis.dist(data.x = lth[c(1,4)], data.y = ltv[c(1,4)], vc=NULL))
MHNtbl[4,4] = mean(mahalanobis.dist(data.x = lth[c(2,3)], data.y = ltv[c(2,3)], vc=NULL))
MHNtbl[4,5] = mean(mahalanobis.dist(data.x = lth[c(2,4)], data.y = ltv[c(2,4)], vc=NULL))
MHNtbl[4,6] = mean(mahalanobis.dist(data.x = lth[c(3,4)], data.y = ltv[c(3,4)], vc=NULL))
MHNtbl[5,1] = mean(mahalanobis.dist(data.x = ltsc[c(1,2)], data.y = ltsy[c(1,2)], vc=NULL))
MHNtbl[5,2] = mean(mahalanobis.dist(data.x = ltsc[c(1,3)], data.y = ltsy[c(1,3)], vc=NULL))
MHNtbl[5,3] = mean(mahalanobis.dist(data.x = ltsc[c(1,4)], data.y = ltsy[c(1,4)], vc=NULL))
MHNtbl[5,4] = mean(mahalanobis.dist(data.x = ltsc[c(2,3)], data.y = ltsy[c(2,3)], vc=NULL))
MHNtbl[5,5] = mean(mahalanobis.dist(data.x = ltsc[c(2,4)], data.y = ltsy[c(2,4)], vc=NULL))
MHNtbl[5,6] = mean(mahalanobis.dist(data.x = ltsc[c(3,4)], data.y = ltsy[c(3,4)], vc=NULL))
MHNtbl[6,1] = mean(mahalanobis.dist(data.x = ltsc[c(1,2)], data.y = ltt[c(1,2)], vc=NULL))
MHNtbl[6,2] = mean(mahalanobis.dist(data.x = ltsc[c(1,3)], data.y = ltt[c(1,3)], vc=NULL))
MHNtbl[6,3] = mean(mahalanobis.dist(data.x = ltsc[c(1,4)], data.y = ltt[c(1,4)], vc=NULL))
MHNtbl[6,4] = mean(mahalanobis.dist(data.x = ltsc[c(2,3)], data.y = ltt[c(2,3)], vc=NULL))
MHNtbl[6,5] = mean(mahalanobis.dist(data.x = ltsc[c(2,4)], data.y = ltt[c(2,4)], vc=NULL))
MHNtbl[6,6] = mean(mahalanobis.dist(data.x = ltsc[c(3,4)], data.y = ltt[c(3,4)], vc=NULL))
MHNtbl[7,1] = mean(mahalanobis.dist(data.x = ltsc[c(1,2)], data.y = ltv[c(1,2)], vc=NULL))
MHNtbl[7,2] = mean(mahalanobis.dist(data.x = ltsc[c(1,3)], data.y = ltv[c(1,3)], vc=NULL))
MHNtbl[7,3] = mean(mahalanobis.dist(data.x = ltsc[c(1,4)], data.y = ltv[c(1,4)], vc=NULL))
MHNtbl[7,4] = mean(mahalanobis.dist(data.x = ltsc[c(2,3)], data.y = ltv[c(2,3)], vc=NULL))
MHNtbl[7,5] = mean(mahalanobis.dist(data.x = ltsc[c(2,4)], data.y = ltv[c(2,4)], vc=NULL))
MHNtbl[7,6] = mean(mahalanobis.dist(data.x = ltsc[c(3,4)], data.y = ltv[c(3,4)], vc=NULL))
MHNtbl[8,1] = mean(mahalanobis.dist(data.x = ltsy[c(1,2)], data.y = ltt[c(1,2)], vc=NULL))
MHNtbl[8,2] = mean(mahalanobis.dist(data.x = ltsy[c(1,3)], data.y = ltt[c(1,3)], vc=NULL))
MHNtbl[8,3] = mean(mahalanobis.dist(data.x = ltsy[c(1,4)], data.y = ltt[c(1,4)], vc=NULL))
MHNtbl[8,4] = mean(mahalanobis.dist(data.x = ltsy[c(2,3)], data.y = ltt[c(2,3)], vc=NULL))
MHNtbl[8,5] = mean(mahalanobis.dist(data.x = ltsy[c(2,4)], data.y = ltt[c(2,4)], vc=NULL))
MHNtbl[8,6] = mean(mahalanobis.dist(data.x = ltsy[c(3,4)], data.y = ltt[c(3,4)], vc=NULL))
MHNtbl[9,1] = mean(mahalanobis.dist(data.x = ltsy[c(1,2)], data.y = ltv[c(1,2)], vc=NULL))
MHNtbl[9,2] = mean(mahalanobis.dist(data.x = ltsy[c(1,3)], data.y = ltv[c(1,3)], vc=NULL))
MHNtbl[9,3] = mean(mahalanobis.dist(data.x = ltsy[c(1,4)], data.y = ltv[c(1,4)], vc=NULL))
MHNtbl[9,4] = mean(mahalanobis.dist(data.x = ltsy[c(2,3)], data.y = ltv[c(2,3)], vc=NULL))
MHNtbl[9,5] = mean(mahalanobis.dist(data.x = ltsy[c(2,4)], data.y = ltv[c(2,4)], vc=NULL))
MHNtbl[9,6] = mean(mahalanobis.dist(data.x = ltsy[c(3,4)], data.y = ltv[c(3,4)], vc=NULL))
MHNtbl[10,1] = mean(mahalanobis.dist(data.x = ltt[c(1,2)], data.y = ltv[c(1,2)], vc=NULL))
MHNtbl[10,2] = mean(mahalanobis.dist(data.x = ltt[c(1,3)], data.y = ltv[c(1,3)], vc=NULL))
MHNtbl[10,3] = mean(mahalanobis.dist(data.x = ltt[c(1,4)], data.y = ltv[c(1,4)], vc=NULL))
MHNtbl[10,4] = mean(mahalanobis.dist(data.x = ltt[c(2,3)], data.y = ltv[c(2,3)], vc=NULL))
MHNtbl[10,5] = mean(mahalanobis.dist(data.x = ltt[c(2,4)], data.y = ltv[c(2,4)], vc=NULL))
MHNtbl[10,6] = mean(mahalanobis.dist(data.x = ltt[c(3,4)], data.y = ltv[c(3,4)], vc=NULL))

write.csv(MHNtbl, "Mahalanobis_distances.csv")

#Euclidean Distances

ltt <- data.matrix(ltt)
ltv <- data.matrix(ltv)
ltsy <- data.matrix(ltsy)
ltsc <- data.matrix(ltsc)
lth <- data.matrix(lth)

lth.ltt <- pdist(lth, ltt, indices.A = NULL, indices.B = NULL)
lth.ltv <- pdist(lth, ltv, indices.A = NULL, indices.B = NULL)
lth.ltsy <- pdist(lth, ltsy, indices.A = NULL, indices.B = NULL)
lth.ltsc <- pdist(lth,ltsy , indices.A = NULL, indices.B = NULL)
ltt.ltv <- pdist(ltt, ltv, indices.A = NULL, indices.B = NULL)
ltt.ltsy <- pdist(ltt,ltsy , indices.A = NULL, indices.B = NULL)
ltt.ltsc <- pdist(ltt, ltsc, indices.A = NULL, indices.B = NULL)
ltv.ltsy <- pdist(ltv, ltsy, indices.A = NULL, indices.B = NULL)
ltv.ltsc <- pdist(ltv, ltsc, indices.A = NULL, indices.B = NULL)
ltsy.ltsc <- pdist(ltsy, ltsc, indices.A = NULL, indices.B = NULL)

lth.ltt <- as.matrix(lth.ltt)
lth.ltv  <- as.matrix(lth.ltv)
lth.ltsy <- as.matrix(lth.ltsy)
lth.ltsc  <- as.matrix(lth.ltsc)
ltt.ltv <- as.matrix(ltt.ltv)
ltt.ltsy <- as.matrix(ltt.ltsy)
ltt.ltsc  <- as.matrix(ltt.ltsc)
ltv.ltsy <- as.matrix(ltv.ltsy)
ltv.ltsc  <- as.matrix(ltv.ltsc)
ltsy.ltsc  <- as.matrix(ltsy.ltsc)

lth.ltt <- data.frame(lth.ltt)
lth.ltv  <- data.frame(lth.ltv)
lth.ltsy <- data.frame(lth.ltsy)
lth.ltsc  <- data.frame(lth.ltsc)
ltt.ltv <- data.frame(ltt.ltv)
ltt.ltsy <- data.frame(ltt.ltsy)
ltt.ltsc  <- data.frame(ltt.ltsc)
ltv.ltsy <- data.frame(ltv.ltsy)
ltv.ltsc  <- data.frame(ltv.ltsc)
ltsy.ltsc  <- data.frame(ltsy.ltsc)

lth.ltt <- unlist(lth.ltt)
lth.ltv  <- unlist(lth.ltv)
lth.ltsy <- unlist(lth.ltsy)
lth.ltsc  <- unlist(lth.ltsc)
ltt.ltv <- unlist(ltt.ltv)
ltt.ltsy <- unlist(ltt.ltsy)
ltt.ltsc  <- unlist(ltt.ltsc)
ltv.ltsy <- unlist(ltv.ltsy)
ltv.ltsc  <- unlist(ltv.ltsc)
ltsy.ltsc  <- unlist(ltsy.ltsc)

mean(lth.ltt)
mean(lth.ltv)
mean(lth.ltsy)
mean(lth.ltsc)
mean(ltt.ltv)
mean(ltt.ltsy)
mean(ltt.ltsc)
mean(ltv.ltsy)
mean(ltv.ltsc)
mean(ltsy.ltsc)

sd(lth.ltt)
sd(lth.ltv)
sd(lth.ltsy)
sd(lth.ltsc)
sd(ltt.ltv)
sd(ltt.ltsy)
sd(ltt.ltsc)
sd(ltv.ltsy)
sd(ltv.ltsc)
sd(ltsy.ltsc)



CI(lth.ltt, ci = 0.95)
CI(lth.ltv, ci = 0.95)
CI(lth.ltsy, ci = 0.95)
CI(lth.ltsc, ci = 0.95)
CI(ltt.ltv, ci = 0.95)
CI(ltt.ltsy, ci = 0.95)
CI(ltt.ltsc, ci = 0.95)
CI(ltv.ltsy, ci = 0.95)